server:
  port: 8081
  servlet:
    context-path: /member
#mybatis配置
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.220.36.202:3306/train_member?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: train_member
    password: train_member

# 降低mapper的日志级别,可以用来显示sql日志
logging:
  level:
    com.sp.trainmember.mapper: trace