# 测试注册接口
POST http://localhost:8081/member/register
Content-Type: application/x-www-form-urlencoded

mobile=123

###
# 获取数据库总条数
GET http://localhost:8081/member/count






###
#测试接口
GET http://localhost:8081/member/test/hello


