POST http://localhost:8080/member/login
Content-Type: application/x-www-form-urlencoded

mobile=13000000000&code=8888

###

#测试发送验证码接口
POST http://localhost:8081/member/sendcode
Content-Type: application/x-www-form-urlencoded

mobile=13000000000

###
# 测试注册接口
POST http://localhost:8081/member/sendcode
Content-Type: application/json

{
  "mobile":"13000000000"
}


# 测试注册接口
POST http://localhost:8081/member/register
Content-Type: application/x-www-form-urlencoded

mobile=12345678901
###
# 获取数据库总条数
GET http://localhost:8080/member/count
Content-Type: application/x-www-form-urlencoded
token:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE3MDM1OTcxMTUsIm1vYmlsZSI6IjEzMDAwMDAwMDAwIiwiaWQiOjE3Mzk2Mzg0OTA5ODkyMDM0NTYsImV4cCI6MTcwMzY4MzUxNSwiaWF0IjoxNzAzNTk3MTE1fQ.MVFCRZBv7u5vc4XRSP-ss3cqJQopMdvpoaT4aHCeJco





###
#测试接口
GET http://localhost:8080/member/test/hello


